### PR TITLE
Add README and tests

### PR DESCRIPTION
**Pull request by ezmiller**
@AnnJohn and @thomastuts this is ready for review.

### CODE REVIEW

**Comment by thomastuts** [comment]
@ezmiller This looks great! One thing I'd change is how we retrieve the data from the API. Students _might_ try to work on these solutions offline — it probably doesn't happen all that often, but we should accommodate them too.

You can do this using `fetch-mock` like I did in [another lab](https://github.com/learn-co-curriculum/react-props-and-state-lab/blob/master/fetch-setup.js).

PS: you also only need to require `whatwg-fetch` once, since it's supposed to create the `fetch` global (like in the spec). This is also handled in the `fetch-setup.js` file I linked above.

**Comment by ezmiller** [comment]
@thomastuts one reason that I'd included the over the internet interaction -- aside from the fact that it is more fun -- is that in the assessment that follows they will be expected to work across the internet. happy to remove that whole dimension of the lab. i just wonder if there are that many students that really need to work completely offline... and since they'll be doing it in the assessment maybe it makes sense to thinking about that?

**Comment by thomastuts** [comment]
@ezmiller I don't think it's going to make much of a difference for the students if the API responses are being mocked or not — they should be using `fetch` with the right URLs anyway, so it doesn't really matter if those come from a live API or a mocked one. I feel like the added inconvenience of having to look for an API token might scare some students off (even though it's really easy, naturally).

**Comment by ezmiller** [comment]
@thomastuts I think it is fine the way it is. I've done this in a past lesson for Flatiron and there weren't any problems that I know of. What you say is also debatable I think. It could be seen as an inconvenience to get an API key, but it also may be exciting to work with real data, and they will be expected to work with live data for the assessment anyway. This could help them build to that experience if that's something new for them. If you or someone else on the Flatiron want to change this later, that is fine, but I will leave it for now. My work with Flatiron is wrapping up for now.

**Pull request merged**
